version: "3"

networks:
  drupalNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.10.0.0/16"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "8021:5432"
    environment:
        POSTGRES_DB: drupaldb
        POSTGRES_USER: drupaluser
        POSTGRES_PASSWORD: drupalpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      drupalNetwork:
        ipv4_address: 172.10.0.10

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - "TZ=America/Sao_Paulo"
    volumes:
      - ./web:/application/web
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      drupalNetwork:
        ipv4_address: 172.10.0.11

  php-fpm:
    container_name: php
    build: docker/php-fpm
    working_dir: /application
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: America/Sao_Paulo"
    volumes:
      - '.:/application'
      - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    networks:
      drupalNetwork:
        ipv4_address: 172.10.0.12


volumes:
  drupal-data:
  db-data: